---
global:
  owner: vjp@gmail.com  
  qsname: sample-project
  regions:
    - us-east-1
  reporting: true
tests:
  taskcat-json:
    parameter_input: wait-task-input.json
    regions:
      - us-east-1
    template_file: wait-task.template

